# Generated by Django 5.1.6 on 2025-02-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('weather', models.CharField(max_length=50)),
                ('economic_condition', models.CharField(max_length=50)),
                ('day_of_week', models.CharField(max_length=20)),
                ('hour_of_day', models.IntegerField()),
                ('speed', models.FloatField()),
                ('is_peak_hour', models.BooleanField()),
                ('event_occurred', models.BooleanField()),
                ('energy_consumption', models.FloatField()),
                ('traffic_density', models.FloatField()),
            ],
        ),
    ]
